name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  size-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Check Size
        run: |
          if ! npx size-limit; then
            echo "Error: File size exceeds the limit!"
            exit 1
          fi
